name = "fluxome"
uuid = "54968383-114b-4554-bbd1-63ec7383be7b"
authors = ["Biotheory Lab"]
version = "0.0.0-DEV"


[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
